apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: tenant-sample-hub # Change this to tenant-sample-tenantnamespace-sample to test the other project
type: Opaque
data:
  foobar: dXNlcm5hbWU= # Base64 encoded value for "username"
  barfoo: cGFzc3dvcmQ= # Base64 encoded value for "password"