apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: testns
type: Opaque
data:
  foobar: dXNlcm5hbWU= # Base64 encoded value for "username"
  barfoo: cGFzc3dvcmQ= # Base64 encoded value for "password"